name: Release Fonts
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get Repo
        uses: actions/checkout@v3

      - name: Get latest version
        run: echo "TAG=$(curl -s 'https://api.github.com/repos/versatiles-org/versatiles-fonts/releases/latest' | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Generate glyphs
        run: npm install; npm run generate

      - name: Generate release file
        run: npm run release

      - name: Add file to release
        run: gh release upload $TAG dist/fonts.tar.gz --clobber
        #uses: svenstaro/upload-release-action@v2
        #with:
        #  repo_token: ${{ secrets.GITHUB_TOKEN }}
        #  file: dist/fonts.tar.gz
        #  tag: ${{ env.TAG }}
        #  overwrite: true

#          run: gh release upload $TAG dist/fonts.tar.gz --clobber -R 'versatiles-org/versatiles-fonts'
