name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Install versatiles_glyphs
        run: |
          curl -Ls \
            "https://github.com/versatiles-org/versatiles-glyphs-rs/raw/refs/heads/main/scripts/install.sh" \
            | sh

      # Get latest release tag and store the tag name (e.g. "v1.2.3") in RELEASE_TAG.
      - name: Get Version
        id: get_tag
        run: echo "RELEASE_TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName')" >> $GITHUB_ENV

      - name: Build fonts
        run: ./scripts/build.sh

      # Upload files to the existing (pre)release
      - name: Upload files to release
        run: gh release upload "${RELEASE_TAG}" dist/*.tar.gz --clobber
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}

      # Publish the release (remove draft, prerelease flags, etc.)
      - name: Publish release
        run: gh release edit "${RELEASE_TAG}" --draft=false --latest --prerelease=false
        env:
          RELEASE_TAG: ${{ env.RELEASE_TAG }}

      - name: Trigger frontend release
        run: |
          curl -XPOST -u "michaelkreil:${{ secrets.PAT_TOKEN }}" "https://api.github.com/repos/versatiles-org/versatiles-frontend/actions/workflows/release.yml/dispatches" --data '{"ref":"main"}'
