name: Release fonts
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - run: 'echo "RELEASE_TAG=v$(jq -r ''.version'' package.json)" >> $GITHUB_ENV'
        name: get version

      - run: npm install

      - run: npm run build
        name: build

      - run: npm run release
        name: prepare release

      - run: gh release create $RELEASE_TAG || true
        name: create release if needed

      - run: gh release upload $RELEASE_TAG --clobber dist/*.tar.gz
        name: add file to release

      - run: gh release edit $RELEASE_TAG --draft=false --latest --prerelease=false
        name: update release
